export const mockUser = {
  id: "user_1",
  name: "Mike Rayner",
  email: "mike@devstash.io",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet",  name: "Snippet",  icon: "Code",       color: "#3b82f6", isSystem: true, contentType: "text" },
  { id: "type_prompt",   name: "Prompt",   icon: "Sparkles",   color: "#8b5cf6", isSystem: true, contentType: "text" },
  { id: "type_command",  name: "Command",  icon: "Terminal",   color: "#f97316", isSystem: true, contentType: "text" },
  { id: "type_note",     name: "Note",     icon: "StickyNote", color: "#fde047", isSystem: true, contentType: "text" },
  { id: "type_link",     name: "Link",     icon: "Link",       color: "#10b981", isSystem: true, contentType: "url"  },
  { id: "type_file",     name: "File",     icon: "File",       color: "#6b7280", isSystem: true, contentType: "file" },
  { id: "type_image",    name: "Image",    icon: "Image",      color: "#ec4899", isSystem: true, contentType: "file" },
] as const;

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Hooks, composition tricks, and server components.",
    isFavorite: true,
    dominantTypeId: "type_snippet",
    itemCount: 24,
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1h ago
  },
  {
    id: "col_2",
    name: "Onboarding Prompts",
    description: "System prompts for customer onboarding flows.",
    isFavorite: true,
    dominantTypeId: "type_prompt",
    itemCount: 12,
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // yesterday
  },
  {
    id: "col_3",
    name: "Shell Toolbox",
    description: "One-liners I always forget — git, docker, k8s.",
    isFavorite: false,
    dominantTypeId: "type_command",
    itemCount: 38,
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "col_4",
    name: "Context Files",
    description: "LLM context prompts for each project.",
    isFavorite: false,
    dominantTypeId: "type_file",
    itemCount: 5,
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "col_5",
    name: "Reading List",
    description: "Articles and docs worth coming back to.",
    isFavorite: false,
    dominantTypeId: "type_link",
    itemCount: 47,
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "col_6",
    name: "Python Snippets",
    description: "Data, scripting, and FastAPI essentials.",
    isFavorite: false,
    dominantTypeId: "type_snippet",
    itemCount: 18,
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "col_7",
    name: "Design Assets",
    description: "Logos, mocks, and reference screenshots.",
    isFavorite: false,
    dominantTypeId: "type_image",
    itemCount: 3,
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "col_8",
    name: "Interview Prep",
    description: "Algorithms, system design, and STAR stories.",
    isFavorite: false,
    dominantTypeId: "type_prompt",
    itemCount: 15,
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "usePrevious hook",
    description: "Track the previous value of any state or prop.",
    contentType: "text" as const,
    content: "export function usePrevious<T>(value: T) {\n  const ref = useRef<T>()\n  useEffect(() => { ref.current = value })\n  return ref.current\n}",
    isFavorite: true,
    isPinned: true,
    language: "typescript",
    itemTypeId: "type_snippet",
    tags: ["react", "hooks"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_2",
    title: "Customer onboarding system prompt",
    description: "System message for the onboarding assistant.",
    contentType: "text" as const,
    content: "You are a friendly onboarding assistant helping new customers get started...",
    isFavorite: true,
    isPinned: false,
    language: null,
    itemTypeId: "type_prompt",
    tags: ["onboarding", "customer"],
    collectionIds: ["col_2"],
  },
  {
    id: "item_3",
    title: "Delete merged git branches",
    description: "Clean up local branches already merged to main.",
    contentType: "text" as const,
    content: "git branch --merged | grep -v '\\*\\|main\\|master' | xargs git branch -d",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    itemTypeId: "type_command",
    tags: ["git", "cleanup"],
    collectionIds: ["col_3"],
  },
  {
    id: "item_4",
    title: "React Query cheatsheet",
    description: "Key patterns for data fetching with TanStack Query.",
    contentType: "url" as const,
    content: null,
    url: "https://tanstack.com/query/latest/docs/react/overview",
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: "type_link",
    tags: ["react", "data-fetching"],
    collectionIds: ["col_5"],
  },
  {
    id: "item_5",
    title: "Flatten nested list",
    description: "Recursively flatten an arbitrarily nested Python list.",
    contentType: "text" as const,
    content: "def flatten(lst):\n    return [x for item in lst for x in (flatten(item) if isinstance(item, list) else [item])]",
    isFavorite: false,
    isPinned: false,
    language: "python",
    itemTypeId: "type_snippet",
    tags: ["python", "utils"],
    collectionIds: ["col_6"],
  },
];

export const mockStats = {
  totalItems: 12,
  totalCollections: 8,
  totalFavorites: 3,
  itemsLimit: 50,
  collectionsLimit: 3,
};
